service: default
runtime: custom
env: flex
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
automatic_scaling:
  cpu_utilization:
    target_utilization: 0.95
  min_num_instances: 1
  max_num_instances: 2
  max_concurrent_requests: 80
env_variables:
  NODE_ENV: "production"
  DATABASE_URL: "file:./dev.db"
liveness_check:
  path: "/liveness_check"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
readiness_check:
  path: "/readiness_check"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300  